# Human Resources EDA
- This notebook focus on practicing Python libraries such as pandas and numpy on an Exploratory Data Analysis environment.
- This notebook uses datasets from [Davide Polizzi Dataset on Kaggle](https://www.kaggle.com/datasets/davidepolizzi/hr-data-set-based-on-human-resources-data-set/data?select=tbl_Perf.csv)
- Because the focus is practicing Python, I will try to explain each steps

In [5]:
# Importing libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot
import seaborn as sns

## 1. Data Exploration
- For a initial analysis we first must understand what the datasets have inside of them, such as columns names, the number of rows and columns (shape), and the datatypes of each column
- We must do this to all the datasets, after all, we are "curious" to know what they have

### Exploring the dataset `tbl_Employee`

In [47]:
# Loading the csv to a variable and printing the 5 first rows
df_employee = pd.read_csv('datasets/tbl_Employee.csv')
df_employee.head(5)

,EmpID,EmpName,EngDt,TermDt,DepID,GenderID,RaceID,MgrID,DOB,PayRate,Level
0,1,"Nash, Kay K",01/01/2015,29/May/2017,8,1,1,1,12/Feb/1987,NaN,1
1,2,"Simpson, Raymond X",01/01/2015,NaN,7,0,4,2,15/Nov/1982,NaN,1
2,3,"Devlin, Kay M",06/10/2015,24/Jun/2019,10,1,5,3,22/Feb/1986,NaN,1
3,4,"Massie, Elisabeth V",01/01/2015,NaN,4,1,2,4,25/May/1977,NaN,1
4,5,"Mead, Catherine N",22/05/2015,15/Jul/2020,8,1,1,1,04/Apr/1995,NaN,2

In [48]:
# Printing the number ofr (rows, columns)
df_employee.shape

(1562, 11)

In [49]:
# Printing all the columns of the DataFrame
df_employee.columns

Index(['EmpID', 'EmpName', 'EngDt', 'TermDt', 'DepID', 'GenderID', 'RaceID',
       'MgrID', 'DOB', 'PayRate', 'Level'],
      dtype='str')

In [50]:
# Printing the type of each column from the DataFrame
df_employee.dtypes

EmpID         int64
EmpName         str
EngDt           str
TermDt          str
DepID         int64
GenderID      int64
RaceID        int64
MgrID         int64
DOB             str
PayRate     float64
Level         int64
dtype: object

In [51]:
# Printing the number of null values in each column
df_employee.isnull().sum()

EmpID          0
EmpName        0
EngDt          0
TermDt      1118
DepID          0
GenderID       0
RaceID         0
MgrID          0
DOB            0
PayRate     1562
Level          0
dtype: int64

In [46]:
# Printing the total of null values in the DataFrame
df_employee.isnull().sum().sum()

np.int64(2680)

### Exploring the dataset `tbl_Action`

In [26]:
# Loading the csv to a variable and printing the 5 first rows
df_action = pd.read_csv('datasets/tbl_Action.csv')
df_action.head(5)

   ActID  ActionID  EmpID  EffectiveDt
0      1        10      1  01/Jan/2015
1      2        10      2  01/Jan/2015
2      3        10      3  06/Oct/2015
3      4        10      4  01/Jan/2015
4      5        10      5  22/May/2015

In [27]:
# Printing the number of (rows, columns)
df_action.shape

(2586, 4)

In [28]:
# Printing all the columns of the DataFrame
df_action.columns

Index(['ActID', 'ActionID', 'EmpID', 'EffectiveDt'], dtype='str')

In [29]:
# Printing the type of each column from the DataFrame
df_action.dtypes

ActID          int64
ActionID       int64
EmpID          int64
EffectiveDt      str
dtype: object

In [44]:
# Printing the total of null values in the DataFrame
df_action.isnull().sum()

ActID          0
ActionID       0
EmpID          0
EffectiveDt    0
dtype: int64

In [45]:
# Printing the total of null values in the DataFrame
df_action.isnull().sum().sum()

np.int64(0)

### Exploring the dataset `tbl_Perf`

In [38]:
# Loading the csv to a variable and printing the 5 first rows
df_performance = pd.read_csv('datasets/tbl_Performance.csv')
df_performance

      PerfID  EmpID  Rating     PerfDate
0          1      1       1  31/Dec/2015
1          2      2       2  31/Dec/2015
2          3      3       2  31/Dec/2015
3          4      4       4  31/Dec/2015
4          5      5       2  31/Dec/2015
...      ...    ...     ...          ...
9600    9601   1558       3  31/Dec/2023
9601    9602   1559       2  31/Dec/2023
9602    9603   1560       4  31/Dec/2023
9603    9604   1561       2  31/Dec/2023
9604    9605   1562       2  31/Dec/2023

[9605 rows x 4 columns]

In [39]:
# Printing the number ofr (rows, columns)
df_performance.shape

(9605, 4)

In [40]:
# Printing all the columns of the DataFrame
df_performance.columns

Index(['PerfID', 'EmpID', 'Rating', 'PerfDate'], dtype='str')

In [41]:
# Printing the type of each column from the DataFrame
df_performance.dtypes

PerfID      int64
EmpID       int64
Rating      int64
PerfDate      str
dtype: object

In [43]:
# Printing the total of null values in the DataFrame
df_performance.isnull().sum()

np.int64(0)

In [52]:
# Printing the total of null values in the DataFrame
df_performance.isnull().sum().sum()

np.int64(0)

## 2. DataData Cleaning & Preparation

After analyzing the DataFrames, I identified several points that need to be addressed to ensure a high-quality analysis. Here are the planned steps:

1. **Column Renaming**: Some column names are not intuitive. I will rename them to be more descriptive and obvious, facilitating the learning process and code readability.
2. **Data Type Conversion**: Several columns containing date values are currently stored as strings. Converting these to `datetime` objects is fundamental for time-series analysis and plotting accurate graphs.
3. **Feature Engineering**: As a specific requirement for this project, I will split the full names of employees into two distinct columns: `First Name` and `Last Name`.
4. **Handling Missing Values**: I will identify and treat null values to prevent bias or errors in future calculations.
5. **Data Merging**: Finally, I will merge all relevant tables into a single master DataFrame. Consolidating employee data will allow for deeper insights and demonstrates the process of joining tables efficiently.