# Revision - Level 2 - 23/04/2026
- Revision abut `.groupby()`

In [1]:
import pandas as pd

## ⚔️ MISSÃO 1 — Receita por região

👉 Crie uma coluna:
revenue = price * quantity

Depois:

👉 Agrupe por `region` e calcule:
- receita total
- quantidade total vendida

👉 Pergunta:
- qual região gera mais receita?
- isso está ligado à quantidade ou ao preço?

In [2]:
df = pd.read_csv('ecommerce_orders.csv')
df

,order_id,customer_id,region,category,price,quantity,payment_method,rating
0,1,101,North,Electronics,1200,1,Credit Card,5
1,2,102,South,Clothing,80,2,Debit Card,4
2,3,103,North,Groceries,10,10,Cash,3
3,4,104,East,Electronics,900,1,Credit Card,4
4,5,105,West,Clothing,60,3,Cash,2
5,6,101,North,Electronics,1100,1,Credit Card,5
6,7,106,South,Groceries,15,8,Debit Card,3
7,8,107,East,Clothing,70,2,Credit Card,4
8,9,108,West,Electronics,1300,1,Credit Card,5
9,10,109,North,Groceries,12,12,Cash,2
10,11,110,South,Clothing,90,1,Debit Card,3
11,12,111,East,Electronics,1000,1,Credit Card,4
12,13,112,West,Groceries,11,9,Cash,2
13,14,113,North,Clothing,75,2,Debit Card,4
14,15,114,South,Electronics,950,1,Credit Card,5
15,16,115,East,Groceries,14,7,Cash,3
16,17,116,West,Clothing,65,2,Credit Card,4
17,18,117,North,Electronics,1250,1,Credit Card,5
18,19,118,South,Groceries,13,11,Cash,3
19,20,119,East,Clothing,85,2,Debit Card,4

In [3]:
df.shape

(20, 8)

In [5]:
df.size

160

In [6]:
df['revenue'] = df['price']*df['quantity']
df

,order_id,customer_id,region,category,price,quantity,payment_method,rating,revenue
0,1,101,North,Electronics,1200,1,Credit Card,5,1200
1,2,102,South,Clothing,80,2,Debit Card,4,160
2,3,103,North,Groceries,10,10,Cash,3,100
3,4,104,East,Electronics,900,1,Credit Card,4,900
4,5,105,West,Clothing,60,3,Cash,2,180
5,6,101,North,Electronics,1100,1,Credit Card,5,1100
6,7,106,South,Groceries,15,8,Debit Card,3,120
7,8,107,East,Clothing,70,2,Credit Card,4,140
8,9,108,West,Electronics,1300,1,Credit Card,5,1300
9,10,109,North,Groceries,12,12,Cash,2,144
10,11,110,South,Clothing,90,1,Debit Card,3,90
11,12,111,East,Electronics,1000,1,Credit Card,4,1000
12,13,112,West,Groceries,11,9,Cash,2,99
13,14,113,North,Clothing,75,2,Debit Card,4,150
14,15,114,South,Electronics,950,1,Credit Card,5,950
15,16,115,East,Groceries,14,7,Cash,3,98
16,17,116,West,Clothing,65,2,Credit Card,4,130
17,18,117,North,Electronics,1250,1,Credit Card,5,1250
18,19,118,South,Groceries,13,11,Cash,3,143
19,20,119,East,Clothing,85,2,Debit Card,4,170

In [11]:
df.groupby('region').agg({
    'revenue': 'sum',
    'quantity': 'sum',
    'price': 'sum'
})

        revenue  quantity  price
region
East       2308        13   2069
North      3944        27   3647
South      1463        23   1148
West       1709        15   1436

The region that contributed more in revenue was the North region, when comparing the price as well, we can see that both quantity an price in the North region havean impact on the revenue, but we could not saythat quantity interferes so much in revenue, since the South region is the second in quantity but the last in revnue, so based only on the columns: revenue, quantity and price, we can say that quantity does not interefere as much as price.

## ⚔️ MISSÃO 2 — Performance por categoria

👉 Agrupe por `category` e calcule:
- média de preço
- média de rating
- total de vendas (quantity)

👉 Pergunta:
- qual categoria tem melhor avaliação?
- existe relação entre preço e rating?

In [12]:
df.groupby('category').agg({
    'price': 'mean',
    'rating': 'mean',
    'quantity': 'sum'
})

              price    rating  quantity
category
Clothing       75.0  3.571429        14
Electronics  1100.0  4.714286         7
Groceries      12.5  2.666667        57

The best rating category is Eletronics.

I do not know, because I oly have three columns on this groupby, and there is no relation whatsoever on how ratings interfere with price, a much deep analysis would be needed to understand how other data interferes with price.

## ⚔️ MISSÃO 3 — Cliente mais valioso

👉 Agrupe por `customer_id` e calcule:
- total gasto (revenue)
- número de pedidos

👉 Pergunta:
- quem é o cliente mais valioso?
- ele compra pouco e caro ou muito e barato?

In [13]:
df.groupby('customer_id').agg({
    'revenue': 'sum',
    'order_id': 'count'
})

             revenue  order_id
customer_id
101             2300         2
102              160         1
103              100         1
104              900         1
105              180         1
106              120         1
107              140         1
108             1300         1
109              144         1
110               90         1
111             1000         1
112               99         1
113              150         1
114              950         1
115               98         1
116              130         1
117             1250         1
118              143         1
119              170         1

By the columns of `revenue` and `order_id` the most valuable customer is the customer 101, it has the biggest revenue and place more orders than the rest.

## ⚔️ MISSÃO 4 — Forma de pagamento

👉 Agrupe por `payment_method` e calcule:
- receita total
- número de pedidos
- média de rating

👉 Pergunta:
- qual método gera mais receita?
- existe diferença na satisfação?

In [14]:
df.groupby('payment_method').agg({
    'revenue': 'sum',
    'order_id': 'count',
    'rating': 'mean'
})

                revenue  order_id    rating
payment_method
Cash                764         6  2.500000
Credit Card        7970         9  4.555556
Debit Card          690         5  3.600000

Credit Card is the method that makes the biggest revenue.

Based on the mean rating the three mthods have almost the same rating, but based on the rating and the number of orders. By using the number of orderswe can deduce that probably customers prefer to use the credit card as their favorite payment metod.