# Exploratory Data Analysis from RAWG database

## Import and loading files

### Import all libraries

In [45]:
import pandas as pd
from mysql import connector
import numpy as np
import seaborn as sns
import matplotlib.pyplothow to get statistics of a dataframe as plt

## Connecting with the database

In [23]:
from dotenv import load_dotenv
import os

# Here I load my variables that I already created
load_dotenv()

True

In [24]:
# Then get them to use here in my notebook
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")

In [25]:
# Stablishing connection with database
connection = connector.connect(
    host=MYSQL_HOST,
    user=MYSQL_USER,
    password=MYSQL_PASSWORD,
    database=MYSQL_DATABASE
)

In [26]:
query = "SELECT * FROM game_data_observatory.games"

## Load a database table to my DataFrame

In [27]:
# Loading my table and closing the coonnection
df = pd.read_sql(query, con=connection)
connection.close()

/tmp/ipykernel_20124/2191961794.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=connection)

In [28]:
df

,id,name,released,rating,ratings_count,metacritic,genres,platforms,tags,esrb_rating
0,25,Middle-earth: Shadow of War,2017-09-27,3.86,1385,82.0,"Action, RPG","PC, Xbox One, PlayStation 4, Android","Singleplayer, Steam Achievements, Full control...",Mature
1,28,Red Dead Redemption 2,2018-10-26,4.59,5498,96.0,Action,"PC, PlayStation 4, Xbox One","Singleplayer, Multiplayer, Atmospheric, Great ...",Mature
2,32,Destiny 2,2017-09-06,3.52,2670,82.0,"Action, Shooter","PlayStation 4, Xbox One, PC, Web, Xbox Series ...","Singleplayer, Multiplayer, Full controller sup...",Teen
3,39,Prey,2017-05-05,4.28,2244,80.0,"Action, Shooter, RPG","Xbox One, PC, PlayStation 4","Singleplayer, Steam Achievements, Full control...",Mature
4,41,Little Nightmares,2017-04-27,4.04,1639,81.0,"Action, Adventure, Platformer","iOS, PlayStation 4, PC, Xbox One, Nintendo Switch","Singleplayer, Steam Achievements, Full control...",NaN
...,...,...,...,...,...,...,...,...,...,...
115,58812,Control,2019-08-27,4.14,2045,84.0,"Action, Shooter, Adventure","Xbox Series S/X, PlayStation 5, Xbox One, Play...","Singleplayer, Full controller support, Atmosph...",Mature
116,257201,Star Wars Jedi: Fallen Order,2019-11-15,4.13,2278,80.0,"Action, Adventure","PlayStation 4, PC, PlayStation 5, Xbox One","Singleplayer, Full controller support, Atmosph...",Teen
117,274755,Hades,2020-09-17,4.42,2093,93.0,"Action, Adventure, RPG, Indie","PlayStation 5, Xbox Series S/X, PlayStation 4,...","Singleplayer, Full controller support, Atmosph...",Teen
118,290856,Apex Legends,2019-02-04,3.63,2418,80.0,"Action, Shooter","PlayStation 4, Nintendo Switch, macOS, PC, Xbo...","Multiplayer, Full controller support, Atmosphe...",Teen
119,326292,Fall Guys: Ultimate Knockout,2020-08-04,3.73,1355,80.0,"Action, Sports, Casual, Massively Multiplayer,...","Xbox One, PlayStation 4, PC, Nintendo Switch, ...","Steam Achievements, Full controller support, O...",Everyone

## Initial Data Exploration

In [43]:
df.head()

,id,name,released,rating,ratings_count,metacritic,genres,platforms,tags,esrb_rating
0,25,Middle-earth: Shadow of War,2017-09-27,3.86,1385,82.0,"Action, RPG","PC, Xbox One, PlayStation 4, Android","Singleplayer, Steam Achievements, Full control...",Mature
1,28,Red Dead Redemption 2,2018-10-26,4.59,5498,96.0,Action,"PC, PlayStation 4, Xbox One","Singleplayer, Multiplayer, Atmospheric, Great ...",Mature
2,32,Destiny 2,2017-09-06,3.52,2670,82.0,"Action, Shooter","PlayStation 4, Xbox One, PC, Web, Xbox Series ...","Singleplayer, Multiplayer, Full controller sup...",Teen
3,39,Prey,2017-05-05,4.28,2244,80.0,"Action, Shooter, RPG","Xbox One, PC, PlayStation 4","Singleplayer, Steam Achievements, Full control...",Mature
4,41,Little Nightmares,2017-04-27,4.04,1639,81.0,"Action, Adventure, Platformer","iOS, PlayStation 4, PC, Xbox One, Nintendo Switch","Singleplayer, Steam Achievements, Full control...",NaN

In [30]:
df.shape

(120, 10)

In [32]:
df.columns

Index(['id', 'name', 'released', 'rating', 'ratings_count', 'metacritic',
       'genres', 'platforms', 'tags', 'esrb_rating'],
      dtype='str')

In [39]:
df.describe()

                  id      rating  ratings_count  metacritic
count     120.000000  120.000000     120.000000  113.000000
mean    19022.808333    4.051917    2496.116667   85.469027
std     51600.017319    0.401247    1172.451315    6.000105
min        25.000000    2.600000     523.000000   70.000000
25%      3283.250000    3.817500    1712.250000   81.000000
50%      4688.000000    4.130000    2227.000000   86.000000
75%     12785.750000    4.380000    2880.750000   90.000000
max    326292.000000    4.690000    7384.000000   96.000000

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             120 non-null    int64
 1   name           120 non-null    str
 2   released       120 non-null    object
 3   rating         120 non-null    float64
 4   ratings_count  120 non-null    int64
 5   metacritic     113 non-null    float64
 6   genres         120 non-null    str
 7   platforms      120 non-null    str
 8   tags           120 non-null    str
 9   esrb_rating    104 non-null    str
dtypes: float64(2), int64(2), object(1), str(5)
memory usage: 51.4+ KB

In [38]:
df.isnull().sum()

id                0
name              0
released          0
rating            0
ratings_count     0
metacritic        7
genres            0
platforms         0
tags              0
esrb_rating      16
dtype: int64

In [52]:
df[df.isnull().any(axis=1)].head()

,id,name,released,rating,ratings_count,metacritic,genres,platforms,tags,esrb_rating
4,41,Little Nightmares,2017-04-27,4.04,1639,81.0,"Action, Adventure, Platformer","iOS, PlayStation 4, PC, Xbox One, Nintendo Switch","Singleplayer, Steam Achievements, Full control...",NaN
12,613,Bastion,2011-07-20,4.14,1670,86.0,"Action, Adventure, RPG, Indie","PlayStation 4, PS Vita, Xbox One, PC, iOS, Lin...","Singleplayer, Steam Achievements, Full control...",NaN
14,766,Warframe,2013-03-25,3.42,2115,73.0,"Action, Shooter, RPG, Massively Multiplayer","iOS, Xbox Series S/X, PlayStation 5, PlayStati...","Singleplayer, Multiplayer, steam-trading-cards...",NaN
25,3144,Super Meat Boy,2010-10-20,3.98,1771,87.0,"Indie, Platformer","Linux, Nintendo Switch, Wii U, Xbox 360, PlayS...","Singleplayer, Steam Achievements, Full control...",NaN
28,3254,Journey,2012-03-13,4.32,2462,92.0,"Adventure, Family, Indie","PC, iOS, PlayStation 4, PlayStation 3","Singleplayer, Steam Achievements, Multiplayer,...",NaN

In [56]:
dfdf.duplicated().sum()

np.int64(0)

## Univariate Analysis

## Bivariate Analysis

## Dealing With Missing Values

## Correlation Analysis